Import CVX codes and fix bug is "is bound to" step.
Argonaut "is bound to" steps were failing to recognize Codeable Concepts and not looking for codings inside them. Instead we were binding `code.coding.code` which didn't really provide helpful error messages.

```
And Immunization.vaccineCode.coding.code is bound to http://hl7.org/fhir/sid/cvx
    ...
    TypeError: 'NoneType' object is not iterable
```

vs.

```
And Immunization.vaccineCode is bound to http://hl7.org/fhir/sid/cvx
    Assertion Failed: Immunization.vaccineCode is missing field "coding".
    {
      "text": "mixed respiratory vaccine"
    }
```

This affected:
* Immunizations
* Lab results
* Problems
* Procedures
* Smoking status
* Vital signs